import type { FieldDef, SectionDef } from "./schema";

const PREFIX = "prm"; // GM_config id

function el<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  className?: string,
  text?: string
): HTMLElementTagNameMap[K] {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function isVisible(def: FieldDef): def is Exclude<FieldDef, { type: "hidden" }> {
  return def.type !== "hidden";
}

/**
 * Turns the flat DOM generated by GM_config into a two-pane settings window:
 * section navigation on the left, "title + description | control" rows, search
 * and a sticky footer. Called from GM_config's open event.
 */
export function enhanceSettingsUI(
  frame: HTMLElement,
  config: GM_configStruct,
  sections: SectionDef[]
) {
  const wrapper = frame.querySelector<HTMLElement>(`#${PREFIX}_wrapper`);
  if (!wrapper) return;

  bindFrameEvents(frame, config);

  const header = wrapper.querySelector<HTMLElement>(`#${PREFIX}_header`)!;
  const buttonsHolder = wrapper.querySelector<HTMLElement>(`#${PREFIX}_buttons_holder`)!;
  const holders = Array.from(
    wrapper.querySelectorAll<HTMLElement>(".section_header_holder")
  );

  // ---- Panels and rows ----
  const panels: HTMLElement[] = [];
  const rows: { row: HTMLElement; panelIndex: number }[] = [];
  const validators: (() => void)[] = [];

  sections.forEach((section, index) => {
    const panel = holders[index];
    if (!panel) return;
    panels.push(panel);

    panel.classList.add("rpm-panel");
    panel.querySelector(".section_header")?.remove();
    panel.querySelector(".section_desc")?.remove();

    const head = el("div", "rpm-panel-head");
    head.append(el("h2", "rpm-panel-title", section.title));
    if (section.desc) head.append(el("p", "rpm-panel-desc", section.desc));
    panel.prepend(head);

    for (const def of section.fields) {
      const field = config.fields[def.key];
      const row = field?.wrapper;
      if (!field || !row) continue;

      if (!isVisible(def)) {
        row.hidden = true;
        continue;
      }

      buildRow(row, def, section.title);
      rows.push({ row, panelIndex: index });

      if (def.type === "text" && def.validate) {
        const input = field.node as HTMLInputElement;
        const hint = el("div", "rpm-row-error");
        hint.hidden = true;
        row.append(hint);
        const check = () => {
          const message = def.validate!(input.value);
          input.classList.toggle("rpm-invalid", message !== null);
          hint.textContent = message ?? "";
          hint.hidden = message === null;
        };
        input.addEventListener("input", check);
        validators.push(check);
      }
    }
  });
  validators.forEach((v) => v());

  // ---- Layout: header / (nav + content) / footer ----
  const titleBlock = el("div", "rpm-title-block");
  while (header.firstChild) titleBlock.append(header.firstChild);

  const search = el("input", "rpm-search");
  search.type = "search";
  search.placeholder = "Поиск по настройкам";
  search.setAttribute("aria-label", "Поиск по настройкам");

  header.classList.add("rpm-header");
  header.append(titleBlock, search);

  const nav = el("nav", "rpm-nav");
  const content = el("div", "rpm-content");
  const empty = el("div", "rpm-empty", "Ничего не найдено");
  empty.hidden = true;
  content.append(...panels, empty);

  const body = el("div", "rpm-body");
  body.append(nav, content);

  // ---- Footer ----
  const saveBtn = buttonsHolder.querySelector<HTMLButtonElement>(`#${PREFIX}_saveBtn`)!;
  const closeBtn = buttonsHolder.querySelector<HTMLButtonElement>(`#${PREFIX}_closeBtn`)!;
  const resetLink = buttonsHolder.querySelector<HTMLAnchorElement>(`#${PREFIX}_resetLink`)!;

  saveBtn.textContent = "Сохранить";
  saveBtn.title = "Сохранить настройки";
  saveBtn.className = "rpm-btn rpm-btn-primary";
  closeBtn.textContent = "Закрыть";
  closeBtn.title = "Закрыть окно";
  closeBtn.className = "rpm-btn";
  resetLink.textContent = "Сбросить к значениям по умолчанию";
  resetLink.title = "Вернуть все поля к значениям по умолчанию (изменения нужно сохранить)";
  resetLink.className = "rpm-reset";

  const dirtyNote = el("span", "rpm-dirty", "Есть несохранённые изменения");
  dirtyNote.hidden = true;
  const setDirty = (dirty: boolean) => {
    dirtyNote.hidden = !dirty;
  };

  buttonsHolder.classList.add("rpm-footer");
  buttonsHolder.replaceChildren(resetLink, dirtyNote, closeBtn, saveBtn);

  content.addEventListener("input", () => setDirty(true));
  content.addEventListener("change", () => setDirty(true));
  resetLink.addEventListener("click", () => {
    setTimeout(() => {
      validators.forEach((v) => v());
      setDirty(true);
    });
  });
  saveBtn.addEventListener("click", () => setDirty(false));

  wrapper.replaceChildren(header, body, buttonsHolder);

  // ---- Navigation and search ----
  let active = 0;

  const navButtons = sections.map((section, index) => {
    const button = el("button", "rpm-nav-item", section.title);
    button.type = "button";
    button.addEventListener("click", () => {
      search.value = "";
      active = index;
      render();
      content.scrollTop = 0;
    });
    nav.append(button);
    return button;
  });

  function render() {
    const query = search.value.trim().toLowerCase();
    frame.classList.toggle("rpm-searching", query !== "");

    const matches = new Array(panels.length).fill(0);
    for (const { row, panelIndex } of rows) {
      const match = query === "" || (row.dataset.search ?? "").includes(query);
      row.hidden = !match;
      if (match) matches[panelIndex]++;
    }

    panels.forEach((panel, index) => {
      panel.hidden = query === "" ? index !== active : matches[index] === 0;
    });
    navButtons.forEach((button, index) => {
      button.classList.toggle("rpm-active", query === "" && index === active);
    });
    empty.hidden = query === "" || matches.some((count) => count > 0);
  }

  search.addEventListener("input", render);
  search.addEventListener("keydown", (e) => {
    if (e.key === "Escape" && search.value !== "") {
      e.stopPropagation();
      search.value = "";
      render();
    }
  });

  render();
  frame.focus();
}

function buildRow(row: HTMLElement, def: Exclude<FieldDef, { type: "hidden" }>, sectionTitle: string) {
  const control = row.querySelector<HTMLElement>(`[id^="${PREFIX}_field_"]`);
  const label = row.querySelector<HTMLElement>(".field_label");
  if (!control) return;

  row.classList.add("rpm-row", `rpm-row-${def.type}`);

  const text = el("div", "rpm-row-label");
  if (def.type === "button") {
    text.append(el("div", "rpm-row-title", def.title));
  } else if (label) {
    label.classList.add("rpm-row-title");
    text.append(label);
  }
  if (def.desc) text.append(el("div", "rpm-row-desc", def.desc));

  const controlBox = el("div", "rpm-row-control");
  controlBox.append(control);

  row.replaceChildren(text, controlBox);
  row.dataset.search = `${def.title} ${def.desc ?? ""} ${sectionTitle}`.toLowerCase();

  // The whole row toggles a switch, not just the tiny control
  if (def.type === "checkbox") {
    row.addEventListener("click", (e) => {
      const target = e.target as HTMLElement;
      if (target === control || target.closest("label")) return;
      (control as HTMLInputElement).click();
    });
  }
}

/** Listeners on the frame element itself survive reopening, so bind only once. */
function bindFrameEvents(frame: HTMLElement, config: GM_configStruct) {
  if (frame.dataset.rpmBound) return;
  frame.dataset.rpmBound = "true";

  frame.tabIndex = -1;
  frame.addEventListener("mousedown", (e) => {
    if (e.target === frame) (config as any).close();
  });
  frame.addEventListener("keydown", (e) => {
    if (e.key === "Escape") (config as any).close();
  });
}
